
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

gym.nombre=Titanium Gym
gym.moneda=MXN
gym.horario=06:00 - 22:00
sistema.version=1.0
sistema.baseDatos=clientes.dat
